wandb: Starting wandb agent üïµÔ∏è
2021-11-09 12:38:16,063 - wandb.wandb_agent - INFO - Running runs: []
2021-11-09 12:38:16,518 - wandb.wandb_agent - INFO - Agent received command: run
2021-11-09 12:38:16,518 - wandb.wandb_agent - INFO - Agent starting run with config:
	confidence_scale: 1.7187312623371471
	target_entropy: -0.15830819159234988
	use_entropy: True
2021-11-09 12:38:16,560 - wandb.wandb_agent - INFO - About to run command: python3 src/main.py --train --wandb
2021-11-09 12:38:21,571 - wandb.wandb_agent - INFO - Running runs: ['3i0qfc18']
wandb: Currently logged in as: jjshoots (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
-----------------------
Using Device cuda:0
-----------------------
wandb: wandb version 0.12.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.0
wandb: Syncing run 8754
wandb:  View project at https://wandb.ai/jjshoots/UA3SAC_gym
wandb:  View sweep at https://wandb.ai/jjshoots/UA3SAC_gym/sweeps/l22tvp9t
wandb:  View run at https://wandb.ai/jjshoots/UA3SAC_gym/runs/3i0qfc18
wandb: Run data is saved locally in /home/taij/e2sac/wandb/run-20211109_123835-3i0qfc18
wandb: Run `wandb offline` to turn off syncing.
XIO:  fatal IO error 0 (Success) on X server ":99"
      after 597 requests (597 known processed) with 10 events remaining.
2021-11-09 15:57:26,344 - wandb.wandb_agent - INFO - Cleaning up finished run: 3i0qfc18
wandb: Terminating and syncing runs. Press ctrl-c to kill.
/usr/bin/xvfb-run: line 186: kill: (556528) - No such process
/home/taij/.conda/envs/robocar/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
